name: 'Codepipeline Webhook Action'
description: 'Codepipeline Webhook Action'
inputs:
  webhook_url:
    description: 'URL of the Webhook'
    required: true
  method:
    description: 'Method for the REST Webhook call'
    required: false
  body:
    description: 'body for the REST Webhook call in case of POST, PUT, PATCH methods'
    required: false

runs:
  using: 'node12'
  main: 'build/index.js'
